version: '3'

networks:
  laravel:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-laravel
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-laravel
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks:
        - laravel
  mysql:
    image: mysql:5.7.22
    container_name: mysql-laravel
    restart: unless-stopped
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel